version: '3'
services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  elastic:
    image: "elasticsearch:7.9.0"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: "logstash:7.9.0"
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/logstash.conf:/usr/share/logstash/config/pipelines/logstash.conf:ro
    command: bash -c "bin/logstash-plugin install logstash-codec-avro && bin/logstash-plugin install logstash-output-stomp && bin/logstash-plugin install logstash-codec-avro_schema_registry && bin/logstash-plugin install logstash-codec-json && logstash"
    environment:
      - discovery.type=single-node
      - XPACK_MONITORING_ENABLED=false
      - ELASTIC_HOST=http://localhost:9200
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5046:5046"
  kibana:
    image: "kibana:7.9.0"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
  gateway:
    image: "nginx:1.19-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx_api_gateway/gateway.conf:/etc/nginx/nginx.conf