version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 7091:7091
      - 8123:8123
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      SPIGET_RESOURCES: "274,28140,2124"
      TZ: "Europe/London"
      ENABLE_JMX: "true"
      JMX_HOST: "localhost"
      USE_AIKAR_FLAGS: "true"
      COPY_CONFIG_DEST: "/data"
      PLUGINS_SYNC_UPDATE: "false"
    volumes:
      - E:\work\storage\minecraft:/data
      - E:\work\storage\minecraft\shared\configs:/config
      - E:\work\storage\minecraft\shared\plugins:/plugins
    stdin_open: true
    tty: true